services:
  - type: web
    name: blitzapp
    env: node
    plan: free
    buildCommand: yarn --frozen-lockfile --prod=false && blitz build && blitz prisma migrate deploy
    startCommand: blitz start
    envVars:
      # ⚠️  First deployment of this blueprint will fail because the app will be built before the database
      # After DB is built, click in the UI to manually `deploy latest commit`
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: blitzapp-db
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true

databases:
  - name: blitzapp-db
    plan: free
